[General]
eccentricity=0.0
#0.462
src=Blondin
Porb_day=9.3
inclination_deg=90
Mopt=23
Ropt=36
Mdot_wind_msun_per_yr=4e-6
v_inf_km_s=1700
beta=0.8
[Wake]
wake_factor_density=3
#wake_phase_width=0.03
wake_extension=0.1
streamlines_rg_fac=10
wake_geometry_choice=1
# 1   wake is between pos_ns - wake_width .. pos_ns + wake_width
# 2   wake is between pos_ns - wake_width .. pos_ns
# 3 "1"+circle at the NS position
# 4 "2"+circle at the NS position
[Calc]
