[General]
src=Vela X-1
eccentricity=0.0898
Porb_day=8.964
omega_PL=152.59
inclination_deg=80
Mopt=22
Ropt=30
# set 3: 
#Mdot_wind_msun_per_yr=7e-7
#beta=1.0
#v_inf_km_s=700
# set 1'
Mdot_wind_msun_per_yr=2e-6
beta=0.5
v_inf_km_s=1700
#
[Wake]
wake_factor_density=30
#wake_phase_width=0.03
wake_extension=0.3
wake_width_rg_fac=10
wake_geometry_choice=2
#
# 1   wake is between pos_ns - wake_width .. pos_ns + wake_width
# 2   wake is between pos_ns - wake_width .. pos_ns
# 3 "1"+circle at the NS position
# 4 "2"+circle at the NS position
[Calc]
[Plot]
NH_min_plot=0.8e22
NH_max_plot=1e25
move_zero_phase_to_mid_eclipse=True