[General]
eccentricity=0.462
src=GX 301−2
Porb_day=41.470
omega_PL=310.4
inclination_deg=55
Mopt=50
Ropt=62
Mdot_wind_msun_per_yr=1e-5
beta=1.75
v_inf_km_s=305
[Wake]
wake_factor_density=3
#wake_phase_width=0.03
wake_extension=0.1
streamlines_rg_fac=10
wake_geometry_choice=2
#
# 1   wake is between pos_ns - wake_width .. pos_ns + wake_width
# 2   wake is between pos_ns - wake_width .. pos_ns
# 3 "1"+circle at the NS position
# 4 "2"+circle at the NS position
[Calc]
[Plot]
NH_min_plot=1e23
NH_max_plot=1.2e25
